<table>
<tr>
<td><img src="/pobjeda/public/img/search1.jpg" alt="logo"/></td>
<td>
<h2 style='font-family:Verdana; color:rgb(111,111,233);'>Rezultat pretrage</h2>
</td>
</tr>

</table>
<hr />
<?php
$tabstil = "font-family:'Trebuchet MS', Arial, Helvetica, sans-serif;width:100%;border-collapse:collapse;";
$zagstil = " text-align:left;padding-left: 5px;padding-bottom: 5px;font-size: 14px;background-color:rgb(81,91,147);color:#ffffff;";
$sadrstil = "font-size:1em;border:1px solid #98bf21;padding:10px 7px 10px 10px;background-color: rgb(221, 223 ,234);border: 1px solid rgb(122, 123 ,155);font-family: Tahoma;font-size: 15px;color: rgb(111,111,200);";
$naslovstil = "font-family:Cambria;font-size:17px; color:rgb(111,111,222);";

if(isset($rez1)){

if($opcija=='1'){
echo "<p style='".$naslovstil."'>Packing List</p>";
echo "<table border='1' style='".$tabstil. "'>";
echo "<tr><th style='" .$zagstil."'>Shipment_Number</th><th style='" .$zagstil."'>Sender_Name</th><th style='" .$zagstil."'>Sender_Code</th><th style='" .$zagstil."'>Receiver_Name</th>".
"<th style='" .$zagstil."'>Receiver_Code</th></tr>";
foreach($rez1 as $k){
echo "<tr>";
$stil = "background-color: rgb(222,222,244); padding:10px;";
echo "<td style='".$sadrstil."'>" .$k['Shipment_Number'] . "</td><td style='".$sadrstil."'>".$k['Sender_Name'] . "</td><td style='".$sadrstil."'>"  . $k['Sender_Code'] ."</td>".
                    "<td style='".$sadrstil."'>" . $k['Receiver_Name']."</td>"."<td style='".$sadrstil."'>" . $k['Receiver_Code']."</td>";
echo "</tr>";
}
echo "</table>";

}
else if($opcija == '2'){
echo "<p style='>".$naslovstil."'>Palete</p>";
echo "<table border='1' style='".$tabstil. "'>";
echo "<tr><th style='" .$zagstil."'>ID Palete</th><th style='" .$zagstil."'>GS1_Code</th><th style='" .$zagstil."'>Item_Type</th><th style='" .$zagstil."'>Order</th>".
"</tr>";
foreach($rez1 as $k){
echo "<tr>";
$stil = "background-color: rgb(222,222,244); padding:10px;";
echo "<td style='".$sadrstil."'>" .$k['idPalete'] . "</td><td style='".$sadrstil."'>".$k['GS1_Code'] . "</td><td style='".$sadrstil."'>"  . $k['Item_Type'] ."</td>".
                    "<td style='".$sadrstil."'>" . $k['Order']."</td>";;
echo "</tr>";
}
echo "</table>";
}
else if($opcija == '3'){
echo "<p style='>".$naslovstil."'>Artupal</p>";
echo "<table border='1' style='".$tabstil. "'>";
echo "<tr><th style='" .$zagstil."'>ID Artupal</th><th style='" .$zagstil."'>Product_Code</th><th style='" .$zagstil."'>Description</th><th style='" .$zagstil."'>Lot_Number</th>".
"<th style='" .$zagstil."'>Quantity</th><th style='" .$zagstil."'>Unit_Of_Measure</th><th style='" .$zagstil."'>Count_Of_Units</th></tr>";
foreach($rez1 as $k){
echo "<tr>";
$stil = "background-color: rgb(222,222,244); padding:10px;";
echo "<td style='".$sadrstil."'>" .$k['idArtupal'] . "</td><td style='".$sadrstil."'>".$k['Product_Code'] . "</td><td style='".$sadrstil."'>"  . $k['Description'] ."</td>".
                    "<td style='".$sadrstil."'>" . $k['Lot_Number']."</td>". "<td style='".$sadrstil."'>" . $k['Quantity']."</td>".
                    "<td style='".$sadrstil."'>" . $k['Unit_Of_Measure']."</td>". "<td style='".$sadrstil."'>" . $k['Count_Of_Units']."</td>";
echo "</tr>";
}
echo "</table>";
}

else if($opcija == '4'){
echo "<p style='>".$naslovstil."'>Paketi</p>";
echo "<table border='1' style='".$tabstil. "'>";
echo "<tr><th style='" .$zagstil."'>ID Paket</th><th style='" .$zagstil."'>Item_Number</th><th style='" .$zagstil."'>Unique Number</th>".
"<th style='" .$zagstil."'>Production_Date</th><th style='" .$zagstil."'>Country_Code</th><th style='" .$zagstil."'>Site_Code</th></tr>";
foreach($rez1 as $k){
echo "<tr>";
$stil = "background-color: rgb(222,222,244); padding:10px;";
echo "<td style='".$sadrstil."'>" .$k['idPaketi'] . "</td><td style='".$sadrstil."'>".$k['Item_Number'] . "</td><td style='".$sadrstil."'>"  . $k['Unique_Number'] ."</td>".
                    "<td style='".$sadrstil."'>" . $k['Production_Date']."</td>".
                    "<td style='".$sadrstil."'>" . $k['Country_Code']."</td>". "<td style='".$sadrstil."'>" . $k['Site_Code']."</td>";
echo "</tr>";
}
echo "</table>";
}

if(isset($artupal)&& count($artupal)!=0){
echo "<br />";
echo "<p style='>".$naslovstil."'>Palete/Artupal- Broj palete: ".$brpalete."</p>";
echo "<table border='1' style='".$tabstil. "'>";
echo "<tr><th style='" .$zagstil."'>ID Artupal</th><th style='" .$zagstil."'>Product_Code</th><th style='" .$zagstil."'>Description</th><th style='" .$zagstil."'>Lot_Number</th></tr>".
"<th style='" .$zagstil."'>Quantity</th><th style='" .$zagstil."'>Unit_Of_Measure</th><th style='" .$zagstil."'>Count_Of_Units</th></tr>";
foreach($artupal as $k){
echo "<tr>";
$stil = "background-color: rgb(222,222,244); padding:10px;";
echo "<td style='".$sadrstil."'>" .$k['idArtupal'] . "</td><td style='".$sadrstil."'>".$k['Product_Code'] . "</td><td style='".$sadrstil."'>"  . $k['Description'] ."</td>".
                    "<td style='".$sadrstil."'>" . $k['Lot_Number']."</td>". "<td style='".$sadrstil."'>" . $k['Quantity']."</td>".
                    "<td style='".$sadrstil."'>" . $k['Unit_Of_Measure']."</td>". "<td style='".$sadrstil."'>" . $k['Count_Of_Units']."</td>";
echo "</tr>";
}
echo "</table>"; 
}

if(isset($paket)&& count($paket)!=0){
echo "<br />";
echo "<p style='>".$naslovstil."'>Palete/Artupal/Paket- Broj artupala: ".$brartupal."</p>";
echo "<table border='1' style='".$tabstil. "'>";
echo "<tr><th style='" .$zagstil."'>ID Paket</th><th style='" .$zagstil."'>Item_Number</th><th style='" .$zagstil."'>Unique_Number</th><th style='" .$zagstil."'>Production_Date</th>".
"<th style='" .$zagstil."'>Country_Code</th><th style='" .$zagstil."'>Site_Code</th></tr>";
foreach($paket as $k){
echo "<tr>";
$stil = "background-color: rgb(222,222,244); padding:10px;";
echo "<td style='".$sadrstil."'>" .$k['idPaketi'] . "</td><td style='".$sadrstil."'>".$k['Item_Number'] . "</td><td style='".$sadrstil."'>"  . $k['Unique_Number'] ."</td>".
                    "<td style='".$sadrstil."'>" . $k['Production_Date']."</td>". "<td style='".$sadrstil."'>" . $k['Country_Code']."</td>".
                    "<td style='".$sadrstil."'>" . $k['Site_Code']."</td>";
echo "</tr>";
}
echo "</table>"; 
}



}
?>